name: Echo Workflow

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    # outputs:
    #      matrix: ${{ steps.read_file.outputs.matrix }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Read AWS Policy JSON File
      id: read_file  
      run: |
        content=$(<policy.json)
        echo "JSON File Content: $content"

      
        # JSON=$(cat ./policy.json)
        # echo "::set-output name=matrix::${JSON//'%'/'%25'}"

    - name: Run a one-line script
      run: |
        echo "${{ steps.read_file.outputs.content }}"
