name: Echo Workflow

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    # outputs:
    #      matrix: ${{ steps.read_file.outputs.matrix }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Read AWS Policy JSON File
      id: read_file  
      run: |
        content=$(<policy.json)
        echo "JSON File Content: $content" >> "$GITHUB_OUTPUT"
        
        #echo "::set-output name=content::$content"

    - name: Run a one-line script
      run: |
        echo "${{ steps.read_file.output.* }}"
